/**
 * Serialize a typed {@link Workflow} to GitHub Actions YAML.
 *
 * Uses the `yaml` package (YAML 1.2 core schema), so the workflow trigger key
 * `on` is preserved as a string key rather than being coerced to the boolean
 * `true` (the classic YAML 1.1 footgun that bites js-yaml users).
 */

import type { Workflow } from "@github-actions-workflow-ts/lib";
import { stringify } from "yaml";

const HEADER = `# GENERATED by @keystone/platform — do not edit by hand.
# Regenerate: pnpm --filter @keystone/platform generate:workflows
# Every deploy job emits the DoraEvent telemetry step; that is what keeps DORA
# metrics comparable across teams (ADR-0002). Change the generator, not the YAML.`;

export function workflowToYaml(workflow: Workflow): string {
  // lineWidth: 0 disables wrapping so long run scripts stay on intact lines.
  return `${HEADER}\n\n${stringify(workflow.workflow, { lineWidth: 0 })}`;
}
