"""Service scaffolding for `devex init` / `devex adopt`.

Pure file-writing logic (no network), so it is testable with a temp dir. The CI
workflow YAML is NOT rendered here — it is produced by shelling out to the
@keystone/platform generator (single source for the pipeline shape); init writes
the wrapper + package.json that make that one command's worth of setup explicit.

`init` writes the golden-path skeleton; `adopt` reuses the same writer with
overwrite disabled, so it adds Keystone artifacts to an existing repo without
ever clobbering app code.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

LANGUAGES = ("python", "go", "clojure", "typescript")
_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

#: Framework install spec (Git, no registry — see .claude/rules/releasing.md).
_FRAMEWORK_SPEC = "github:MauricioPereaA/keystone#main&path:/packages/platform-framework"


@dataclass
class ScaffoldResult:
    created: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)


def is_valid_service_name(name: str) -> bool:
    return bool(_NAME_RE.match(name))


def pr_template() -> str:
    """The golden-path PR template body (used by `devex init` and `devex pr`)."""
    return (
        "<!-- Keystone PR template. Work ID required in the title: 'feat(scope): FIN-123 ...'. -->\n\n"
        "## Work ID\n\nCloses FIN-\n\n"
        "## What changed and why\n\n-\n\n"
        "## How it was tested\n\n- [ ] Unit / property-based / contract\n- [ ] Manual\n\n"
        "## Checklist\n\n"
        "- [ ] Tests added/updated\n"
        "- [ ] No new env vars missing from `.env.example`\n"
        "- [ ] Two approvals + green CI before merge\n"
    )


def _package_json(service: str) -> str:
    data = {
        "name": service,
        "private": True,
        "type": "module",
        "scripts": {"generate:workflows": "node scripts/generate-workflows.mjs"},
        "dependencies": {"@keystone/platform": _FRAMEWORK_SPEC},
    }
    return json.dumps(data, indent=2) + "\n"


def _generate_wrapper() -> str:
    return (
        "// Generated by `devex init`. Emits the golden-path CI workflows from\n"
        "// @keystone/platform. Run: pnpm install && pnpm generate:workflows\n"
        'import { mkdirSync, readFileSync, writeFileSync } from "node:fs";\n'
        "import {\n"
        "  generateIntegrationPipeline,\n"
        "  generatePrPipeline,\n"
        "  workflowToYaml,\n"
        '} from "@keystone/platform/workflows";\n\n'
        "// apiSpec is optional — when absent the generated contract step auto-detects\n"
        "// openapi.yaml|yml|json at the repo root at runtime.\n"
        'const { service, language, apiSpec } = JSON.parse(readFileSync("keystone.json", "utf8"));\n'
        'mkdirSync(".github/workflows", { recursive: true });\n'
        "for (const wf of [\n"
        "  generatePrPipeline({ repo: service, language, apiSpec }),\n"
        "  generateIntegrationPipeline({ repo: service, language, apiSpec }),\n"
        "]) {\n"
        "  writeFileSync(`.github/workflows/${wf.filename}.yml`, workflowToYaml(wf), \"utf8\");\n"
        "  process.stdout.write(`generated .github/workflows/${wf.filename}.yml\\n`);\n"
        "}\n"
    )


def _readme(service: str, language: str) -> str:
    return (
        f"# {service}\n\n"
        f"A Keystone golden-path service ({language}). Bootstrapped with `devex init`.\n\n"
        "## Adopt the golden path\n\n"
        "```bash\n"
        "pnpm install                 # pulls @keystone/platform\n"
        "pnpm generate:workflows      # emits .github/workflows/* from the framework\n"
        "uv tool install \"git+https://github.com/MauricioPereaA/keystone#subdirectory=packages/devex-cli\"\n"
        "devex hooks install          # local shift-left validation\n"
        "```\n\n"
        "CI, telemetry (DORA), and conventions are inherited from `@keystone/platform`\n"
        "and `conventions.json` — you don't reinvent them.\n"
    )


def scaffold_service(target: Path, service: str, language: str, *, overwrite: bool) -> ScaffoldResult:
    """Write the golden-path files into `target`. Existing files are skipped unless overwrite."""
    files = {
        "keystone.json": json.dumps({"service": service, "language": language}, indent=2) + "\n",
        ".github/pull_request_template.md": pr_template(),
        "package.json": _package_json(service),
        "scripts/generate-workflows.mjs": _generate_wrapper(),
        "README.md": _readme(service, language),
    }
    result = ScaffoldResult()
    for rel, content in files.items():
        path = target / rel
        if path.exists() and not overwrite:
            result.skipped.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        result.created.append(path)
    return result
